name: Update manifestgen

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"

jobs:
  update-manifestgen:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.x
      - name: Update component versions
        id: update
        run: |
          RELEASE_VERSION=$(curl -s https://api.github.com/repos/fluxcd/flux2/releases | jq -r 'sort_by(.published_at) | .[-1] | .tag_name')
          CURRENT_VERSION=$(go list -m all | grep github.com/fluxcd/flux2 | awk '{print $2}')
          if [[ "${RELEASE_VERSION}" != "${CURRENT_VERSION}" ]]; then
            go mod edit -require github.com/fluxcd/flux2@${RELEASE_VERSION}
            go mod tidy
          fi
          git diff

          PR_TITLE="Update Flux to ${RELEASE_VERSION}"
          PR_BODY="- github.com/fluxcd/flux2 to ${RELEASE_VERSION}%0A  https://github.com/fluxcd/flux2/releases/${RELEASE_VERSION}%0A"
          echo "::set-output name=pr_body::$PR_BODY"
          echo "::set-output name=pr_title::$PR_TITLE"
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
            token: ${{ secrets.BOT_GITHUB_TOKEN }}
            commit-message: |
              ${{ steps.update.outputs.pr_title }}

              ${{ steps.update.outputs.pr_body }}
            committer: GitHub <noreply@github.com>
            author: fluxcdbot <fluxcdbot@users.noreply.github.com>
            signoff: true
            title: ${{ steps.update.outputs.pr_title }}
            body: |
              ${{ steps.update.outputs.pr_body }}
            branch: update-components
            labels: |
              area/build
            reviewers: ${{ secrets.ASSIGNEES }}
      - name: Check output
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
